web_server:
  port: 8081
  port_redirect: 8082
  index: 
    route: /
    files: frontend/build/web
  static:
    route: /static
    files: frontend/build/web
  static_folders:
    - uploads
    - static-files
    - .well-known
  ssl:
    enabled: 0
    key_path: /ssl/KEY.key
    cert_path: /ssl/CERT.crt
    port: 443
  urls:
    base: https://YOUR-DOMAIN.com
    base_server: https://YOUR-DOMAIN.com
  cors_urls:
    - http://127.0.0.1:8081
    - http://127.0.0.1:3030
    - http://localhost:8081
    - http://localhost:3030
    - http://localhost:8082
    - http://127.0.0.1:8082
mongodb:
  url: YOUR-MONGODB-URL-HERE
  db_name: YOUR-MONGODB-DATABASE-NAME-HERE
  url_vector_tiles_actual: MONGODB-URL-HERE
notifications:
  email:
    from: notify@YOUR-DOMAIN.com
    to_admin: YOUR-EMAIL-HERE
    mailchimp:
      api_key: YOUR-MAILCHIMP-API-KEY-HERE
      server_prefix: PREFIX-HERE
    sendgrid:
      api_key: YOUR-SENDGRID-API-KEY-HERE
logging: yes
debug: yes
log_level: 20
log_tracker:
  min_per_hour: 1
  max_per_hour: 150
mapbox:
  access_token: YOUR-TOKEN-HERE
stripe:
  api_key: KEY-HERE
  secret: SECRET-HERE
twilio:
  account_sid: ACCOUNT-ID-HERE
  auth_token: TOKEN-HERE
  from: '+1xxxyyyzzzz'
  test_mode: 1
  message_service_id: 'ID-HERE'
  message_template_ids:
    verificationCode: 'HX7b10a66539a9ecdb8c73707b0a8077ed'
    eventHostMoney: 'HX9625cb83d3a4b3e84a2ae62f4db7b3ed'
    eventAttendConfirmed: 'HX5da7deb996d255eb1c6df4b7826ab853'
    eventJoined: 'HX7ff7d2ebb867ab64dd5f686f938f1890'
    eventInvite: 'HX05c2d8d6b5ecb2292bd0b2498035e1d6'
    eventNotEnoughHosts: 'HX5b85c5caa99bc06f3f9b1be0dfc54862'
    eventSubscriptionCanceled: 'HX074082bd43f9202c322c28f295d7f530'
    eventFeedback: 'HX13b393ae2c058ef16d11c4b532cbe0d3'
    ambassadorUpdateFollowUp: 'HXb98060731c8db441ba613193007b89c4'
mercury:
  test_mode: 1
  api_token: TOKEN-HERE
  accounts:
    - key: MercuryEndUserFunds
      account_id: ACCOUNT-ID
  recipients:
    - key: MercuryUserRevenue
      account_number: 'ACCOUNT-NUMBER'
      routing_number: 'ROUTING-NUMBER'